source 'https://rubygems.org'
gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem "rake"
gem 'bcrypt'
gem 'sinatra-flash'
group :test do
  gem 'rspec'
  gem 'capybara'
  gem "rspec-sinatra"
  gem 'database_cleaner'
end
